# Generated by Django 5.0.9 on 2026-08-06 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('godown_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('van', 'Van')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tally_godown_guid', models.CharField(blank=True, max_length=100)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='godowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_type', models.CharField(choices=[('van_load', 'Van load'), ('van_unload', 'Van unload'), ('warehouse_transfer', 'Warehouse transfer')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('transfer_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.godown')),
                ('to_godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.godown')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to='fleet.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('variance_reason', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('opening', 'Opening balance'), ('van_load', 'Van load'), ('van_unload', 'Van unload'), ('sale', 'Sale'), ('sale_return', 'Sale return'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, help_text='Signed: positive = stock in, negative = stock out.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text="e.g. 'invoice', 'stock_transfer'", max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='catalog.item')),
            ],
            options={
                'indexes': [models.Index(fields=['godown', 'item', 'created_at'], name='inventory_s_godown__3c3cff_idx')],
            },
        ),
        migrations.CreateModel(
            name='VanStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.item')),
            ],
            options={
                'unique_together': {('godown', 'item')},
            },
        ),
    ]
