# Generated by Django 5.0.9 on 2026-08-08 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGatewaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_gateway_url', models.URLField(blank=True)),
                ('_fcm_server_key_encrypted', models.TextField(blank=True, db_column='fcm_server_key_encrypted')),
                ('_sms_gateway_api_key_encrypted', models.TextField(blank=True, db_column='sms_gateway_api_key_encrypted')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
