# Generated by Django 5.0.9 on 2026-08-08 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationgatewaysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('expense_approved', 'Expense approved (push)'), ('expense_rejected', 'Expense rejected (push)'), ('delivery_otp', 'Delivery OTP (SMS)')], max_length=50, unique=True)),
                ('title_template', models.CharField(blank=True, help_text='Push notification title. Leave blank for SMS-only templates.', max_length=200)),
                ('body_template', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
