# Generated by Django 5.0.9 on 2026-08-09 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('gateway', 'WhatsApp Business API'), ('console', 'Console (no gateway configured)')], max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notificationgatewaysettings',
            name='_whatsapp_access_token_encrypted',
            field=models.TextField(blank=True, db_column='whatsapp_access_token_encrypted'),
        ),
        migrations.AddField(
            model_name='notificationgatewaysettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.CharField(choices=[('expense_approved', 'Expense approved (push)'), ('expense_rejected', 'Expense rejected (push)'), ('delivery_otp', 'Delivery OTP (SMS + WhatsApp)'), ('invoice_ready_whatsapp', 'Invoice ready (WhatsApp)')], max_length=50, unique=True),
        ),
    ]
