ROLE_VAN_SALESMAN = "van_salesman"
ROLE_PRE_SALES = "pre_sales_order_booker"
ROLE_SALES_SUPERVISOR = "sales_supervisor"
ROLE_BACK_OFFICE_ADMIN = "back_office_admin"
ROLE_FINANCE_ACCOUNTS = "finance_accounts"
ROLE_FLEET_MANAGER = "fleet_manager"
ROLE_SYSTEM_IT_ADMIN = "system_it_admin"

ROLE_CHOICES = [
    (ROLE_VAN_SALESMAN, "Van Salesman / Field Sales Executive"),
    (ROLE_PRE_SALES, "Pre-Sales / Order Booker"),
    (ROLE_SALES_SUPERVISOR, "Sales Supervisor / Area Sales Manager"),
    (ROLE_BACK_OFFICE_ADMIN, "Back-Office / Admin User"),
    (ROLE_FINANCE_ACCOUNTS, "Finance / Accounts User"),
    (ROLE_FLEET_MANAGER, "Fleet / Transport Manager"),
    (ROLE_SYSTEM_IT_ADMIN, "System / IT Administrator"),
]

# Permission codes, grouped by domain. Referenced by apps.accounts.permissions.HasRolePermission.
PERM_CATALOG_MANAGE = "catalog.item.manage"
PERM_CATALOG_VIEW = "catalog.item.view"
PERM_CUSTOMERS_MANAGE = "customers.manage"
PERM_CUSTOMERS_VIEW = "customers.view"
PERM_CUSTOMERS_CREDIT_OVERRIDE = "customers.credit_limit.override"
PERM_SALES_INVOICE_CREATE = "sales.invoice.create"
PERM_SALES_ORDER_CREATE = "sales.order.create"
PERM_SALES_RECEIPT_CREATE = "sales.receipt.create"
PERM_SALES_RETURN_CREATE = "sales.return.create"
PERM_SALES_VIEW_OWN = "sales.view_own"
PERM_SALES_VIEW_ALL = "sales.view_all"
PERM_FLEET_TRIP_MANAGE_OWN = "fleet.trip.manage_own"
PERM_FLEET_VEHICLE_MANAGE = "fleet.vehicle.manage"
PERM_FLEET_VIEW_ALL = "fleet.view_all"
PERM_INVENTORY_STOCK_TRANSFER_OWN = "inventory.stock_transfer.create_own"
PERM_INVENTORY_MANAGE = "inventory.manage"
PERM_INTEGRATIONS_SYNC_VIEW = "integrations.sync.view"
PERM_INTEGRATIONS_SYNC_RETRY = "integrations.sync.retry"
PERM_REPORTING_DASHBOARD_VIEW = "reporting.dashboard.view"
PERM_USERS_MANAGE = "users.manage"
PERM_ROLES_MANAGE = "roles.manage"
PERM_EXPENSES_CREATE_OWN = "expenses.create_own"
PERM_EXPENSES_VIEW_ALL = "expenses.view_all"
PERM_EXPENSES_APPROVE = "expenses.approve"
PERM_ATTENDANCE_CREATE_OWN = "attendance.create_own"
PERM_ATTENDANCE_VIEW_ALL = "attendance.view_all"

DEFAULT_ROLE_PERMISSIONS = {
    ROLE_VAN_SALESMAN: [
        PERM_CATALOG_VIEW, PERM_CUSTOMERS_VIEW, PERM_SALES_INVOICE_CREATE, PERM_SALES_ORDER_CREATE,
        PERM_SALES_RECEIPT_CREATE, PERM_SALES_RETURN_CREATE, PERM_SALES_VIEW_OWN,
        PERM_FLEET_TRIP_MANAGE_OWN, PERM_INVENTORY_STOCK_TRANSFER_OWN, PERM_EXPENSES_CREATE_OWN,
        PERM_ATTENDANCE_CREATE_OWN,
    ],
    ROLE_PRE_SALES: [
        PERM_CATALOG_VIEW, PERM_CUSTOMERS_VIEW, PERM_SALES_ORDER_CREATE, PERM_SALES_VIEW_OWN,
        PERM_FLEET_TRIP_MANAGE_OWN, PERM_EXPENSES_CREATE_OWN, PERM_ATTENDANCE_CREATE_OWN,
    ],
    ROLE_SALES_SUPERVISOR: [
        PERM_CATALOG_VIEW, PERM_CUSTOMERS_VIEW, PERM_CUSTOMERS_CREDIT_OVERRIDE, PERM_SALES_VIEW_ALL,
        PERM_FLEET_VIEW_ALL, PERM_REPORTING_DASHBOARD_VIEW, PERM_EXPENSES_VIEW_ALL, PERM_EXPENSES_APPROVE,
        PERM_ATTENDANCE_VIEW_ALL,
    ],
    ROLE_BACK_OFFICE_ADMIN: [
        PERM_CATALOG_MANAGE, PERM_CATALOG_VIEW, PERM_CUSTOMERS_MANAGE, PERM_CUSTOMERS_VIEW,
        PERM_SALES_VIEW_ALL, PERM_INVENTORY_MANAGE, PERM_INTEGRATIONS_SYNC_VIEW,
        PERM_REPORTING_DASHBOARD_VIEW, PERM_USERS_MANAGE, PERM_EXPENSES_VIEW_ALL, PERM_EXPENSES_APPROVE,
        PERM_ATTENDANCE_VIEW_ALL,
    ],
    ROLE_FINANCE_ACCOUNTS: [
        PERM_CATALOG_VIEW, PERM_CUSTOMERS_VIEW, PERM_CUSTOMERS_CREDIT_OVERRIDE, PERM_SALES_VIEW_ALL,
        PERM_INTEGRATIONS_SYNC_VIEW, PERM_INTEGRATIONS_SYNC_RETRY, PERM_REPORTING_DASHBOARD_VIEW,
        PERM_EXPENSES_VIEW_ALL, PERM_EXPENSES_APPROVE, PERM_ATTENDANCE_VIEW_ALL,
    ],
    ROLE_FLEET_MANAGER: [
        PERM_FLEET_VEHICLE_MANAGE, PERM_FLEET_VIEW_ALL, PERM_INVENTORY_MANAGE,
        PERM_REPORTING_DASHBOARD_VIEW,
    ],
    ROLE_SYSTEM_IT_ADMIN: [
        PERM_CATALOG_MANAGE, PERM_CUSTOMERS_MANAGE, PERM_SALES_VIEW_ALL, PERM_FLEET_VEHICLE_MANAGE,
        PERM_INVENTORY_MANAGE, PERM_INTEGRATIONS_SYNC_VIEW, PERM_INTEGRATIONS_SYNC_RETRY,
        PERM_REPORTING_DASHBOARD_VIEW, PERM_USERS_MANAGE, PERM_ROLES_MANAGE,
        PERM_EXPENSES_VIEW_ALL, PERM_EXPENSES_APPROVE, PERM_ATTENDANCE_VIEW_ALL,
    ],
}
