# Generated by Django 5.0.9 on 2026-08-07 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat amount off'), ('percent', 'Percent off'), ('slab', 'Volume/slab discount')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount/percent for flat or percent schemes. Unused for slab schemes — see slabs.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SchemeSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat amount off'), ('percent', 'Percent off')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='catalog.scheme')),
            ],
            options={
                'ordering': ['min_qty'],
            },
        ),
    ]
