# Generated by Django 5.0.9 on 2026-08-08 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_scheme_discount_type_alter_scheme_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeBXGY',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('trigger_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('bonus_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('max_multiples', models.PositiveIntegerField(blank=True, help_text='Cap on how many times the bonus repeats per invoice. Blank = uncapped.', null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('bonus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bxgy_bonuses', to='catalog.item')),
                ('trigger_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bxgy_triggers', to='catalog.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
