# Generated by Django 5.0.9 on 2026-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('van_salesman', 'Van Salesman / Field Sales Executive'), ('pre_sales_order_booker', 'Pre-Sales / Order Booker'), ('sales_supervisor', 'Sales Supervisor / Area Sales Manager'), ('back_office_admin', 'Admin (Back-Office)'), ('finance_accounts', 'Finance / Accounts User'), ('fleet_manager', 'Fleet / Transport Manager'), ('system_it_admin', 'IT Head (System/IT Administrator)')], max_length=50, unique=True),
        ),
    ]
