# Generated by Django 5.0.9 on 2026-08-22 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('requested_role_name', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('van_salesman', 'Van Salesman / Field Sales Executive'), ('pre_sales_order_booker', 'Pre-Sales / Order Booker'), ('sales_supervisor', 'Sales Supervisor / Area Sales Manager'), ('back_office_admin', 'Admin (Back-Office)'), ('finance_accounts', 'Finance / Accounts User'), ('fleet_manager', 'Fleet / Transport Manager'), ('system_it_admin', 'IT Head (System/IT Administrator)')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_signup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
