# Generated by Django 5.0.9 on 2026-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text="Shown on the GST invoice PDF header. Uploaded directly (not via Master Settings approval, same as default_godown) — binary data doesn't fit a ChangeRequest's JSON diff.", null=True, upload_to='branding/'),
        ),
    ]
