# Generated by Django 5.0.9 on 2026-08-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upi_vpa',
            field=models.CharField(blank=True, help_text='Payee UPI ID (e.g. yourcompany@okhdfcbank) that point-of-sale QR codes pay into. Blank means UPI QR codes are unavailable — no gateway account is required, this is a static upi://pay deep link any UPI app can scan.', max_length=100),
        ),
    ]
