# Generated by Django 5.0.9 on 2026-08-06 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_type', models.CharField(choices=[('tally', 'Tally Prime'), ('busy', 'Busy'), ('marg', 'Marg ERP 9+'), ('mock', 'Mock (demo/dev)')], default='mock', max_length=20)),
                ('sync_mode', models.CharField(choices=[('realtime', 'Real-time'), ('batch', 'Scheduled batch')], default='batch', max_length=20)),
                ('batch_interval_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('_credentials_encrypted', models.TextField(blank=True, db_column='credentials_encrypted')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=30)),
                ('local_object_id', models.UUIDField()),
                ('erp_reference_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed (will retry)'), ('failed_permanent', 'Failed (max retries)')], default='pending', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='integration_status_1b61ee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='synclogentry',
            constraint=models.UniqueConstraint(fields=('entity_type', 'local_object_id'), name='unique_sync_log_per_entity'),
        ),
    ]
