# Generated by Django 5.0.9 on 2026-08-08 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_schemebxgy'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='bxgy_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.schemebxgy'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='System-generated free line from a BXGY scheme, not entered by the agent.'),
        ),
    ]
