# Generated by Django 5.0.9 on 2026-08-08 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoiceline_bxgy_scheme_invoiceline_is_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_confirmed_via',
            field=models.CharField(blank=True, choices=[('', 'Not confirmed'), ('signature', 'Signature'), ('otp', 'OTP')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='InvoiceDeliveryOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_otp', to='sales.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
