# Generated by Django 5.0.9 on 2026-08-09 05:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwayBillSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EwayBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (not filed with the government)'), ('filed', 'Filed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('ship', 'Ship')], default='road', max_length=10)),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('transporter_id', models.CharField(blank=True, help_text="Transporter's GSTIN, if any.", max_length=15)),
                ('transporter_name', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ewb_number', models.CharField(blank=True, help_text='The real government-issued EWB number — only ever populated once a live GSP/NIC connection files this bill.', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill', to='sales.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
